## Numpy

In [1]:
import numpy as np

In [8]:
aS = [[0 for x in range(7)]for y in range(7)]
print(aS)

[[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]]


In [4]:
a = np.zeros((8,7))

In [5]:
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# create a one dimensional array

x = np.array([1,2,3,4,5])

y = np.array([1,2,3,4,5])

In [10]:
print(x)

[1 2 3 4 5]


In [12]:
print(y)

[1 2 3 4 5]


In [13]:
type(x)

numpy.ndarray

In [15]:
x.shape

(5,)

In [17]:
y.shape

(5,)

In [18]:
# create 2 dimensional array

z = np.array([[1,2],[3,4]])

In [19]:
print(z)

[[1 2]
 [3 4]]


In [22]:
# to get dimension
z.ndim

2

In [24]:
z.shape

(2, 2)

In [30]:
row = z.shape[0]
column = z.shape[1]

In [31]:
print(row)
print(column)

2
2


In [33]:
z.dtype

dtype('int32')

In [34]:
# creating a multidimensional array

w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[26,27,28]]])
print(w, '\n')
print('The shape of W is', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]] 

The shape of W is (3, 3, 3)


### Accessing specific 

In [36]:
c = np.array([[1,2,3,5],[5,6,7,8]])
print(c)

[[1 2 3 5]
 [5 6 7 8]]


In [40]:
# get a specific element [row,col]

c[0, 2]

3

In [41]:
c[1, -2]

7

In [42]:
# get specific row
c[1, :]

array([5, 6, 7, 8])

In [43]:
# get specific column
c[:, 2]

array([3, 7])

In [44]:
c[0, 1:3:1]

array([2, 3])

In [45]:
f = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(f)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
f[0, 1:6:2]

array([2, 4, 6])

In [48]:
c[0, 3] = 4
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
# 3d array

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
# get specific element (work outside in)
b[0, 1, 1]

4

In [53]:
bN = b[:,1,:]
bN

array([[3, 4],
       [7, 8]])

In [58]:
# replace

b[:,1,:] = [[9,9],[8,8]]

In [59]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])