## Numerical Computation with Numpy

In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kuye_temp = 73
kuye_rainfall = 67
kuye_humidity = 43

In [3]:
kuye_yield_apples = kuye_temp * w1 + kuye_rainfall * w2 + kuye_humidity * w3

In [4]:
kuye_yield_apples

56.8

In [5]:
print(f'The expected yield of apples in kuye is {kuye_yield_apples} tons per hectares')

The expected yield of apples in kuye is 56.8 tons per hectares


In [6]:
# To make the computation easier

kuye = [73, 67, 43]
lag = [91, 88, 64]
sabo = [102, 43, 37]
Hamama = [102, 43, 37]
underG = [69, 96, 70] 

# temperature rainfall and humidity respectively

In [7]:
weights = [w1, w2, w3]

In [8]:
# create afunction to calculate crip yield

def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
    print(result)

In [9]:
kuye

[73, 67, 43]

In [10]:
weights

[0.3, 0.2, 0.5]

###  the use of Zip

In [11]:
# element wise

for item in zip(kuye, weights):
    print(item)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [12]:
# since the output is a tuple 

for k,w in zip(kuye, weights):
    print(k, w)

73 0.3
67 0.2
43 0.5


In [13]:
crop_yield(kuye, weights)

56.8

In [14]:
crop_yield(lag, weights)

76.9

In [15]:
crop_yield(underG, weights)

74.9

## Numpy instead of Python list

In [16]:
import numpy as np

In [17]:
# Numpy array

kuye = np.array([73, 67, 43])

In [18]:
kuye

array([73, 67, 43])

In [19]:
weights = np.array([w1, w2, w3])

In [20]:
weights

array([0.3, 0.2, 0.5])

In [21]:
type(kuye)

numpy.ndarray

In [22]:
weights[0]

0.3

In [23]:
kuye[2]

43

## Operation on Numpy arrays

In [24]:
np.dot(kuye, weights)

56.8

In [25]:
kuye

array([73, 67, 43])

In [26]:
weights

array([0.3, 0.2, 0.5])

In [27]:
# element wise

kuye * weights

array([21.9, 13.4, 21.5])

In [28]:
# Alternatively

(kuye * weights).sum()

56.8

## Benefit of Numpy

**Ease to use**: you can write concise mathematical expression instead of using loops

**Performance**: Numpy operations and functions are implemented internally in C++

In [29]:
# python lists

arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy list 

arr1_np = np.array(arr1)
arr2_np = np.array(arr2) 

In [30]:
%%time

result = 0

for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
result

CPU times: user 3.53 s, sys: 90 ms, total: 3.62 s
Wall time: 4.75 s


833332333333500000

In [31]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 30 ms, sys: 0 ns, total: 30 ms
Wall time: 26.6 ms


-1942957984

## Multi-dimensional Numpy arrays

In [32]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [33]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

We can inspect length of Numpy array using `.shape`

In [34]:
# 2D array

climate_data.shape

(5, 3)

weights

In [35]:
#1D array

weights.shape 

(3,)

In [36]:
#3D array

arr3 = np.array([
    [[11, 12, 13],
     [13, 14, 15]],
    
    [[15, 16, 17],
     [17, 18, 19.5]]])

In [37]:
arr3.shape

(2, 2, 3)

Elements in Numpy array should have the same datatype b'cos of efficiency. Use `.dtype` to check

In [38]:
weights.dtype

dtype('float64')

In [39]:
climate_data.dtype 

dtype('int32')

**N.B**: If an array contains single floating point number, all other elements are also converted to float. 

In [40]:
arr3.dtype 

dtype('float64')

### Matrix multiplication

We can compute yield_apples in all regions using a single matrix multiplication between `climate_data` of shape (5,3) and `weight` of shape (3,). 

In [42]:
climate_data  

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [43]:
weights

array([0.3, 0.2, 0.5])

In [44]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [45]:
# alternatively use @ for matrix multiplication

climate_data @ weights 

array([56.8, 76.9, 81.9, 57.7, 74.9])